SELECT A.*
FROM 
(
SELECT SYSID, SECTION, CELL, BLOCK, OSECTION, OBLOCK, OCELL, MDATE, VACDATE, RFORM
FROM AC_OMS.OMS_IHHIST
WHERE (SECTION IS NOT NULL OR BLOCK IS NOT NULL OR CELL IS NOT NULL) AND MDATE >= TO_DATE('01/01/2021', 'DD/MM/YYYY')

UNION

SELECT SYSID, SECTION, CELL, BLOCK, NULL AS "OSECTION", NULL AS "OBLOCK", NULL AS "OCELL",
    MOVDATE AS "MDATE", NULL AS "VACDATE", RFORM 
FROM AC_OMS.OMS_HA
-- This WHERE condition used to filter out bad data from OMS_HA, whereby an individual
-- is no longer in the jail but it is believed they were from their last known movement
WHERE TRUNC(MOVDATE) >= TO_DATE('01/01/2021', 'DD/MM/YYYY')
    ) A
WHERE (SECTION != 'LEVG' OR BLOCK != 'RC') AND MDATE IS NOT NULL
ORDER BY MDATE