SELECT ACJ_DATE, ACJ_SECT "SECTION", ACJ_BLOCK "BLOCK", ACJ_CELL "CELL", ACJ_BED "BED", SYSID, IN_DATE FROM AC_OMS.OMS_IOT_DAILY_POPULATION_7AM
                WHERE TRUNC(ACJ_DATE) >= TO_DATE('03/09/2022', 'DD/MM/YYYY')
UNION
SELECT ACJ_DATE, ACJ_SECT "SECTION", ACJ_BLOCK "BLOCK", ACJ_CELL "CELL", ACJ_BED "BED", SYSID, IN_DATE FROM AC_OMS.OMS_IOT_DAILY_POPULATION_HA
                WHERE TRUNC(ACJ_DATE) >= TO_DATE('01/01/2021', 'DD/MM/YYYY') AND TRUNC(ACJ_DATE) < TO_DATE('03/09/2022', 'DD/MM/YYYY') 